#Games
fortnite = Game.create(name:"Fortnite", category:"Action")
pubg = Game.create(name:"PlayerUnknown's Battlegrounds", category:"Action")
bttlefld1942 = Game.create(name:"Battlefield 1942", category:"Action")
apex = Game.create(name:"APEX Legends", category:"Action")
red_dead = Game.create(name:"Red Dead Redemption 2", category:"Action")
cod = Game.create(name:"Call of Duty: WWII", category:"Action")
star_wars = Game.create(name:"Star Wars Battlefront II", category:"Action")
gow = Game.create(name:"God of War", category:"Action-Adventure")
last_of_us = Game.create(name:"The Last of Us", category:"Action-Adventure")
spiderman = Game.create(name:"Spiderman", category:"Action-Adventure")
sea_of_thieves = Game.create(name:"Sea of Thieves", category:"Action-Adventure")
zelda = Game.create(name:"The Legend of Zelda: Breath", category:"Action-Adventure")
mario_kart = Game.create(name:"Mario Kart 8 Deluxe", category:"Action-Adventure")
solitude = Game.create(name:"Sea of Solitude", category:"Adventure")
outer_wilds = Game.create(name:"Outer Wilds", category:"Adventure")
minecraft = Game.create(name:"Minecraft", category:"Adventure")
wolf_among_us = Game.create(name:"The Wolf Among Us", category:"Adventure")
super_mario = Game.create(name:"Super Mario Odyssey", category:"Adventure")
tetri = Game.create(name:"Tetris", category:"Puzzle")
snipperclips = Game.create(name:"Snipperclips", category:"Puzzle")
kingdom_hearts = Game.create(name:"Kingdom Hearts III", category:"Role-playing")
anthem = Game.create(name:"Anthem", category:"Role-playing")
cyberpunk = Game.create(name:"Cyberpunk 2077", category:"Role-playing")
stardew_valley = Game.create(name:"Stardew Valley", category:"Role-playing")
cites = Game.create(name:"Cities: Skylines", category:"Simulation")
overcooked2 = Game.create(name:"Overcooked 2", category:"Simulation")
rkt_league = Game.create(name:"Rocket League", category:"Sports")
mdn19 = Game.create(name:"Madden 19", category:"Sports")
nba2k = Game.create(name:"NBA 2K18", category:"Sports")
fifa = Game.create(name:"FIFA 18", category:"Sports")
sc2 = Game.create(name:"FIFA 18", category:"Stategy")
civil = Game.create(name:"Civilizayion VI", category:"Strategy")
csgo = Game.create(name:"Counter-Strike: Global Offensive")

#Systems
pc = System.create(name:"PC")
ps4 = System.create(name:"PlayStation 4")
xb1 = System.create(name:"Xbox One")
swi = System.create(name:"Nintendo Switch")
#Availableons
Availableon.create(system_id: pc.id, game_id: pubg.id)